6-third_line

diff --git a/0x02-shell_redirections/6-third_line b/0x02-shell_redirections/6-third_line
--- a/0x02-shell_redirections/6-third_line
+++ b/0x02-shell_redirections/6-third_line
@@ -1,2 +1,11 @@
-#!/bin/bash
-head -n 3 iacta | tail -n1
+#!/usr/bin/env bash
+#checks if file exists
+file="iacta"
+#checks if file exists
+if [ ! -e "$file" ]; then
+	echo "File not found"
+	exit 1
+fi
+#displays third line of file
+line=$(head -n 3 iacta | tail -n 1)
+echo "$line"
